### PR TITLE
fix: closes #4

### LINKED ISSUE #4: Causes overflow hidden on body, even when acctual modal is not showing
https://github.com/weahead/react-customizable-modal/blob/b332d7bebbe74293b5d6c4426c784aec9fb3a00a/src/containers/Modal.tsx#L39

### PR DESCRIPTION
**Pull request by jb-san**
the problem, was that we used the useBodyScrollLock hook, inside a component that is always rendered, by moving it to a wrapper component, we wont lock the scrolling when just rendering the modal component

### CODE REVIEW

File: example/index.jsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import logo from './logo.svg';
 import AnimatedModal from './components/animatedModal';
 import SwipeInFromBelowModal from './components/SwipeInFromBelowModal';
 import WobblyModal from './components/wobblyModal';
-import { ModalPortal, Modal } from '@weahead/react-customizable-modal';
+import { ModalPortal, Modal } from '../';
```
Comment (michaellopez) [inline example/index.jsx]: @jb-san Do we want this change in the example? Shouldn't it be copy/paste-able? These two changes basically tie it to the repo instead of being portable?

Comment (jb-san) [reply example/index.jsx]: no, its not suposed to be copy pasteable, this should be to test the components and hooks when developing, maybe changing the name to something to be more clear ?
